Models/ErrorViewModel.cs
namespace MVCWebApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Insurance/InsuranceVM.cs
using System.Runtime.CompilerServices;

namespace MVCWebApplication.Models.Insurance
{

    public class InsurancePageVM
    {
        public InsuranceFilterVM InsuranceFilter { get; set; }
        public List<InsuranceDetailVM> InsuranceDetails { get; set; } = new List<InsuranceDetailVM>();
    }
    public class InsuranceDetailVM
    {
        public long ClaimNumber { get; set; }
        public long LineNumber { get; set; }
        public string Member { get; set; }
        public string Provider { get; set; }
        public string ProcedureCode { get; set; }
        public string NetAmount { get; set; }
        public string ClaimReceivedOn { get; set; }
        public string Matching { get; set; }
        public DateTime? ServiceFromDateTime { get; set; }
        public DateTime? ServiceToDateTime { get; set; }
        public string Modifier1 { get; set; }
        public string Modifier2 { get; set; }
        public string Modifier3 { get; set; }
        public string Modifier4 { get; set; }
        public double? ContractedAmount { get; set; }
        public string PlaceOfService { get; set; }
    }

    public class InsuranceFilterVM
    {
        public long? ClaimNumber { get; set; }
        public long? LineNumber { get; set; }
        public List<DuplicateParamVM> DuplicateParams { get; set; } = new List<DuplicateParamVM>();
        public List<string> DuplicateCheck { get; set; } = new List<string>();
        public byte? MatchingCount { get; set; }
    }

    public class DuplicateParamVM
    {
        public string Key { get; set; }
        public string Value { get; set; }
        public bool Selected { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCWebApplication.Models;
using System.Diagnostics;

namespace MVCWebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/InsuranceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using MVCWebApplication.Models.Insurance;
using MVCWebApplication.Repository.Insurance;

namespace MVCWebApplication.Controllers
{
    public class InsuranceController : Controller
    {
        public IInsuranceRepository _repository;

        public InsuranceController(IInsuranceRepository repository)
        {
            _repository = repository;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _repository.GetInsuranceDetails(new InsuranceFilterVM());
            return View(data);
        }

        [HttpPost]
        public async Task<IActionResult> SearchInsurance([FromForm]InsurancePageVM filterVM)
        {
            var data = await _repository.GetInsuranceDetails(filterVM.InsuranceFilter);
            return View("Index", data);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Insurance/Index.cshtml
@using MVCWebApplication.Models.Insurance
@model InsurancePageVM

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("SearchInsurance", "Insurance", FormMethod.Post))
{
    <div class="table-responsive">
        <table class="table table-sm table-borderless">
            <tr>
                <td>Claim Number</td>
                <td>@Html.TextBoxFor(x=>x.InsuranceFilter.ClaimNumber)</td>
            </tr>
            <tr>
                <td>Line Number</td>
                <td>@Html.TextBoxFor(x=>x.InsuranceFilter.LineNumber)</td>
            </tr>
            <tr>
                <td>Duplicate Parameters</td>
                <td>
                    @for (int i = 0; i < Model.InsuranceFilter.DuplicateParams.Count; i++)
                    {
                        @Html.CheckBoxFor(m => m.InsuranceFilter.DuplicateParams[i].Selected)
                        @Html.HiddenFor(m => m.InsuranceFilter.DuplicateParams[i].Key)
                        @Html.HiddenFor(m => m.InsuranceFilter.DuplicateParams[i].Value)
                        @Html.LabelFor(m => m.InsuranceFilter.DuplicateParams[i].Selected,Model.InsuranceFilter.DuplicateParams[i].Value)
                        <br />
                    }
                </td>
            </tr>
            <tr>
                <td>Matching Count</td>
                <td>@Html.TextBoxFor(x=>x.InsuranceFilter.MatchingCount)</td>
            </tr>
        </table>
        <input type="submit" value="Search" />
    </div>
}

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>Claim Number</th>
                <th>Line Number</th>
                <th>Provider</th>
                <th>Procedure Code</th>
                <th>Net Amount</th>
                <th>Received On</th>
                <th>Matching Crietaria</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.InsuranceDetails)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ClaimNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LineNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Provider)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProcedureCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NetAmount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ClaimReceivedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Matching)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCWebApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCWebApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Insurance" asp-action="Index">Insurance</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVCWebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>